# Porta (obrigatório para cloud providers)
server.port=${PORT:8080}
spring.main.banner-mode=off

# Datasource - usar variáveis do Neon
spring.datasource.url=jdbc:postgresql://ep-cool-king-ad8ys097-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_zOTscDCr48Pj
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
