server.port=${PORT:8080}
spring.main.banner-mode=off

# PostgreSQL (rede privada do Railway)
spring.datasource.url=jdbc:postgresql://postgres-w3oz.railway.internal:5432/railway?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=tCxMXQUMGjZXUkkPyPMzqZBKNrjUSxQG
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
